# Server Port (optional)
server.port=${PORT:8080}


# Hibernate / JPA Configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Naming strategy (optional but useful)
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl